version: 0.2
phases:
  pre_build:
    commands:
      - cd services/poll-blog
      - npm install --omit=dev
      - npm test
  build:
    commands:
      - zip -q -r deployment.zip index.mjs
  post_build:
    commands:
      - echo updating $FUNCTION_NAME
      - aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file=fileb://deployment.zip
